import {
  GET_PAISES,
  GET_BY_NAME,
  FILTER_BY_CONTINENT,
  ORDER_BY_NAME,
  GET_DETAILS,
  ORDER_BY_POPULATION,
  GET_LIST_ATIVITIES,
  FILTER_BY_ACTIVITIES
} from "./actions";

/* const initialState = {
  paises: [
    {
      id: "ITA",
      nombre: "Italy",
      bandera: "https://flagcdn.com/w320/it.png",
      continente: "Europe",
      capital: "Rome",
      subregion: "Southern Europe",
      area: 301336,
      poblacion: 59554023,
    },
    {
      id: "BGD",
      nombre: "Bangladesh",
      bandera: "https://flagcdn.com/w320/bd.png",
      continente: "Asia",
      capital: "Dhaka",
      subregion: "Southern Asia",
      area: 147570,
      poblacion: 164689383,
    },
    {
      id: "DNK",
      nombre: "Denmark",
      bandera: "https://flagcdn.com/w320/dk.png",
      continente: "Europe",
      capital: "Copenhagen",
      subregion: "Northern Europe",
      area: 43094,
      poblacion: 5831404,
    },
    {
      id: "QAT",
      nombre: "Qatar",
      bandera: "https://flagcdn.com/w320/qa.png",
      continente: "Asia",
      capital: "Doha",
      subregion: "Western Asia",
      area: 11586,
      poblacion: 2881060,
    },
    {
      id: "PAN",
      nombre: "Panama",
      bandera: "https://flagcdn.com/w320/pa.png",
      continente: "North America",
      capital: "Panama City",
      subregion: "Central America",
      area: 75417,
      poblacion: 4314768,
    },
    {
      id: "MYT",
      nombre: "Mayotte",
      bandera: "https://flagcdn.com/w320/yt.png",
      continente: "Africa",
      capital: "Mamoudzou",
      subregion: "Eastern Africa",
      area: 374,
      poblacion: 226915,
    },
  ],
}; */

const arrayPaises = [
	{id: "NRU", nombre: "Nauru", bandera: "https://flagcdn.com/w320/nr.png", continente: "Oceania", capital: "Yaren", subregion: "Micronesia", area: 21, poblacion: 10834 },
	{id: "GLP", nombre: "Guadeloupe", bandera: "https://flagcdn.com/w320/gp.png", continente: "North America", capital: "Basse-Terre", subregion: "Caribbean", area: 1628, poblacion: 400132 },
	{id: "BOL", nombre: "Bolivia", bandera: "https://flagcdn.com/w320/bo.png", continente: "South America", capital: "Sucre", subregion: "South America", area: 1098581, poblacion: 11673029 },
	{id: "KOR", nombre: "South Korea", bandera: "https://flagcdn.com/w320/kr.png", continente: "Asia", capital: "Seoul", subregion: "Eastern Asia", area: 100210, poblacion: 51780579 },
	{id: "NAM", nombre: "Namibia", bandera: "https://flagcdn.com/w320/na.png", continente: "Africa", capital: "Windhoek", subregion: "Southern Africa", area: 825615, poblacion: 2540916 },
	{id: "FRO", nombre: "Faroe Islands", bandera: "https://flagcdn.com/w320/fo.png", continente: "Europe", capital: "Tórshavn", subregion: "Northern Europe", area: 1393, poblacion: 48865 },
	{id: "USA", nombre: "United States", bandera: "https://flagcdn.com/w320/us.png", continente: "North America", capital: "Washington, D.C.", subregion: "North America", area: 9372610, poblacion: 329484123 },
	{id: "YEM", nombre: "Yemen", bandera: "https://flagcdn.com/w320/ye.png", continente: "Asia", capital: "Sana'a", subregion: "Western Asia", area: 527968, poblacion: 29825968 },
	{id: "ESP", nombre: "Spain", bandera: "https://flagcdn.com/w320/es.png", continente: "Europe", capital: "Madrid", subregion: "Southern Europe", area: 505992, poblacion: 47351567 },
	{id: "AIA", nombre: "Anguilla", bandera: "https://flagcdn.com/w320/ai.png", continente: "North America", capital: "The Valley", subregion: "Caribbean", area: 91, poblacion: 13452 },
	{id: "VCT", nombre: "Saint Vincent and the Grenadines", bandera: "https://flagcdn.com/w320/vc.png", continente: "North America", capital: "Kingstown", subregion: "Caribbean", area: 389, poblacion: 110947 },
	{id: "AND", nombre: "Andorra", bandera: "https://flagcdn.com/w320/ad.png", continente: "Europe", capital: "Andorra la Vella", subregion: "Southern Europe", area: 468, poblacion: 77265 },
	{id: "DJI", nombre: "Djibouti", bandera: "https://flagcdn.com/w320/dj.png", continente: "Africa", capital: "Djibouti", subregion: "Eastern Africa", area: 23200, poblacion: 988002 },
	{id: "MYT", nombre: "Mayotte", bandera: "https://flagcdn.com/w320/yt.png", continente: "Africa", capital: "Mamoudzou", subregion: "Eastern Africa", area: 374, poblacion: 226915 },
	{id: "CHL", nombre: "Chile", bandera: "https://flagcdn.com/w320/cl.png", continente: "South America", capital: "Santiago", subregion: "South America", area: 756102, poblacion: 19116209 },
	{id: "VIR", nombre: "United States Virgin Islands", bandera: "https://flagcdn.com/w320/vi.png", continente: "North America", capital: "Charlotte Amalie", subregion: "Caribbean", area: 347, poblacion: 106290 },
	{id: "CAF", nombre: "Central African Republic", bandera: "https://flagcdn.com/w320/cf.png", continente: "Africa", capital: "Bangui", subregion: "Middle Africa", area: 622984, poblacion: 4829764 },
	{id: "NIC", nombre: "Nicaragua", bandera: "https://flagcdn.com/w320/ni.png", continente: "North America", capital: "Managua", subregion: "Central America", area: 130373, poblacion: 6624554 },
	{id: "CZE", nombre: "Czechia", bandera: "https://flagcdn.com/w320/cz.png", continente: "Europe", capital: "Prague", subregion: "Central Europe", area: 78865, poblacion: 10698896 },
	{id: "BVT", nombre: "Bouvet Island", bandera: "https://flagcdn.com/w320/bv.png", continente: "Antarctica", capital: "Sin Capital", subregion: "Sin Subregion", area: 49, poblacion: 0 },
	{id: "NZL", nombre: "New Zealand", bandera: "https://flagcdn.com/w320/nz.png", continente: "Oceania", capital: "Wellington", subregion: "Australia and New Zealand", area: 270467, poblacion: 5084300 },
	{id: "RUS", nombre: "Russia", bandera: "https://flagcdn.com/w320/ru.png", continente: "Europe", capital: "Moscow", subregion: "Eastern Europe", area: 17098242, poblacion: 144104080 },
	{id: "BFA", nombre: "Burkina Faso", bandera: "https://flagcdn.com/w320/bf.png", continente: "Africa", capital: "Ouagadougou", subregion: "Western Africa", area: 272967, poblacion: 20903278 },
	{id: "PRI", nombre: "Puerto Rico", bandera: "https://flagcdn.com/w320/pr.png", continente: "North America", capital: "San Juan", subregion: "Caribbean", area: 8870, poblacion: 3194034 },
	{id: "FJI", nombre: "Fiji", bandera: "https://flagcdn.com/w320/fj.png", continente: "Oceania", capital: "Suva", subregion: "Melanesia", area: 18272, poblacion: 896444 },
	{id: "TKM", nombre: "Turkmenistan", bandera: "https://flagcdn.com/w320/tm.png", continente: "Asia", capital: "Ashgabat", subregion: "Central Asia", area: 488100, poblacion: 6031187 },
	{id: "MMR", nombre: "Myanmar", bandera: "https://flagcdn.com/w320/mm.png", continente: "Asia", capital: "Naypyidaw", subregion: "South-Eastern Asia", area: 676578, poblacion: 54409794 },
	{id: "ROU", nombre: "Romania", bandera: "https://flagcdn.com/w320/ro.png", continente: "Europe", capital: "Bucharest", subregion: "Southeast Europe", area: 238391, poblacion: 19286123 },
	{id: "STP", nombre: "São Tomé and Príncipe", bandera: "https://flagcdn.com/w320/st.png", continente: "Africa", capital: "São Tomé", subregion: "Middle Africa", area: 964, poblacion: 219161 },
	{id: "TTO", nombre: "Trinidad and Tobago", bandera: "https://flagcdn.com/w320/tt.png", continente: "North America", capital: "Port of Spain", subregion: "Caribbean", area: 5130, poblacion: 1399491 },
	{id: "FRA", nombre: "France", bandera: "https://flagcdn.com/w320/fr.png", continente: "Europe", capital: "Paris", subregion: "Western Europe", area: 551695, poblacion: 67391582 },
	{id: "ABW", nombre: "Aruba", bandera: "https://flagcdn.com/w320/aw.png", continente: "North America", capital: "Oranjestad", subregion: "Caribbean", area: 180, poblacion: 106766 },
	{id: "BGR", nombre: "Bulgaria", bandera: "https://flagcdn.com/w320/bg.png", continente: "Europe", capital: "Sofia", subregion: "Southeast Europe", area: 110879, poblacion: 6927288 },
	{id: "FIN", nombre: "Finland", bandera: "https://flagcdn.com/w320/fi.png", continente: "Europe", capital: "Helsinki", subregion: "Northern Europe", area: 338424, poblacion: 5530719 },
	{id: "COM", nombre: "Comoros", bandera: "https://flagcdn.com/w320/km.png", continente: "Africa", capital: "Moroni", subregion: "Eastern Africa", area: 1862, poblacion: 869595 },
	{id: "HMD", nombre: "Heard Island and McDonald Islands", bandera: "https://flagcdn.com/w320/hm.png", continente: "Antarctica", capital: "Sin Capital", subregion: "Sin Subregion", area: 412, poblacion: 0 },
	{id: "MWI", nombre: "Malawi", bandera: "https://flagcdn.com/w320/mw.png", continente: "Africa", capital: "Lilongwe", subregion: "Eastern Africa", area: 118484, poblacion: 19129955 },
	{id: "MAR", nombre: "Morocco", bandera: "https://flagcdn.com/w320/ma.png", continente: "Africa", capital: "Rabat", subregion: "Northern Africa", area: 446550, poblacion: 36910558 },
	{id: "ESH", nombre: "Western Sahara", bandera: "https://flagcdn.com/w320/eh.png", continente: "Africa", capital: "El Aaiún", subregion: "Northern Africa", area: 266000, poblacion: 510713 },
	{id: "SYR", nombre: "Syria", bandera: "https://flagcdn.com/w320/sy.png", continente: "Asia", capital: "Damascus", subregion: "Western Asia", area: 185180, poblacion: 17500657 },
	{id: "BLM", nombre: "Saint Barthélemy", bandera: "https://flagcdn.com/w320/bl.png", continente: "North America", capital: "Gustavia", subregion: "Caribbean", area: 21, poblacion: 4255 },
	{id: "IRL", nombre: "Ireland", bandera: "https://flagcdn.com/w320/ie.png", continente: "Europe", capital: "Dublin", subregion: "Northern Europe", area: 70273, poblacion: 4994724 },
	{id: "SGS", nombre: "South Georgia", bandera: "https://flagcdn.com/w320/gs.png", continente: "Antarctica", capital: "King Edward Point", subregion: "Sin Subregion", area: 3903, poblacion: 30 },
	{id: "TCA", nombre: "Turks and Caicos Islands", bandera: "https://flagcdn.com/w320/tc.png", continente: "North America", capital: "Cockburn Town", subregion: "Caribbean", area: 948, poblacion: 38718 },
	{id: "ASM", nombre: "American Samoa", bandera: "https://flagcdn.com/w320/as.png", continente: "Oceania", capital: "Pago Pago", subregion: "Polynesia", area: 199, poblacion: 55197 },
	{id: "IMN", nombre: "Isle of Man", bandera: "https://flagcdn.com/w320/im.png", continente: "Europe", capital: "Douglas", subregion: "Northern Europe", area: 572, poblacion: 85032 },
	{id: "CUB", nombre: "Cuba", bandera: "https://flagcdn.com/w320/cu.png", continente: "North America", capital: "Havana", subregion: "Caribbean", area: 109884, poblacion: 11326616 },
	{id: "DZA", nombre: "Algeria", bandera: "https://flagcdn.com/w320/dz.png", continente: "Africa", capital: "Algiers", subregion: "Northern Africa", area: 2381741, poblacion: 44700000 },
	{id: "KWT", nombre: "Kuwait", bandera: "https://flagcdn.com/w320/kw.png", continente: "Asia", capital: "Kuwait City", subregion: "Western Asia", area: 17818, poblacion: 4270563 },
	{id: "MOZ", nombre: "Mozambique", bandera: "https://flagcdn.com/w320/mz.png", continente: "Africa", capital: "Maputo", subregion: "Eastern Africa", area: 801590, poblacion: 31255435 },
	{id: "GBR", nombre: "United Kingdom", bandera: "https://flagcdn.com/w320/gb.png", continente: "Europe", capital: "London", subregion: "Northern Europe", area: 242900, poblacion: 67215293 },
	{id: "GRL", nombre: "Greenland", bandera: "https://flagcdn.com/w320/gl.png", continente: "North America", capital: "Nuuk", subregion: "North America", area: 2166086, poblacion: 56367 },
	{id: "JAM", nombre: "Jamaica", bandera: "https://flagcdn.com/w320/jm.png", continente: "North America", capital: "Kingston", subregion: "Caribbean", area: 10991, poblacion: 2961161 },
	{id: "LKA", nombre: "Sri Lanka", bandera: "https://flagcdn.com/w320/lk.png", continente: "Asia", capital: "Sri Jayawardenepura Kotte", subregion: "Southern Asia", area: 65610, poblacion: 21919000 },
	{id: "AFG", nombre: "Afghanistan", bandera: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png", continente: "Asia", capital: "Kabul", subregion: "Southern Asia", area: 652230, poblacion: 40218234 },
	{id: "NLD", nombre: "Netherlands", bandera: "https://flagcdn.com/w320/nl.png", continente: "Europe", capital: "Amsterdam", subregion: "Western Europe", area: 41850, poblacion: 16655799 },
	{id: "BLZ", nombre: "Belize", bandera: "https://flagcdn.com/w320/bz.png", continente: "North America", capital: "Belmopan", subregion: "Central America", area: 22966, poblacion: 397621 },
	{id: "MDA", nombre: "Moldova", bandera: "https://flagcdn.com/w320/md.png", continente: "Europe", capital: "Chișinău", subregion: "Eastern Europe", area: 33846, poblacion: 2617820 },
	{id: "CHN", nombre: "China", bandera: "https://flagcdn.com/w320/cn.png", continente: "Asia", capital: "Beijing", subregion: "Eastern Asia", area: 9706961, poblacion: 1402112000 },
	{id: "EST", nombre: "Estonia", bandera: "https://flagcdn.com/w320/ee.png", continente: "Europe", capital: "Tallinn", subregion: "Northern Europe", area: 45227, poblacion: 1331057 },
	{id: "TJK", nombre: "Tajikistan", bandera: "https://flagcdn.com/w320/tj.png", continente: "Asia", capital: "Dushanbe", subregion: "Central Asia", area: 143100, poblacion: 9537642 },
	{id: "GUY", nombre: "Guyana", bandera: "https://flagcdn.com/w320/gy.png", continente: "South America", capital: "Georgetown", subregion: "South America", area: 214969, poblacion: 786559 },
	{id: "AUT", nombre: "Austria", bandera: "https://flagcdn.com/w320/at.png", continente: "Europe", capital: "Vienna", subregion: "Central Europe", area: 83871, poblacion: 8917205 },
	{id: "IRN", nombre: "Iran", bandera: "https://flagcdn.com/w320/ir.png", continente: "Asia", capital: "Tehran", subregion: "Southern Asia", area: 1648195, poblacion: 83992953 },
	{id: "MLT", nombre: "Malta", bandera: "https://flagcdn.com/w320/mt.png", continente: "Europe", capital: "Valletta", subregion: "Southern Europe", area: 316, poblacion: 525285 },
	{id: "UKR", nombre: "Ukraine", bandera: "https://flagcdn.com/w320/ua.png", continente: "Europe", capital: "Kyiv", subregion: "Eastern Europe", area: 603500, poblacion: 44134693 },
	{id: "PHL", nombre: "Philippines", bandera: "https://flagcdn.com/w320/ph.png", continente: "Asia", capital: "Manila", subregion: "South-Eastern Asia", area: 342353, poblacion: 109581085 },
	{id: "BMU", nombre: "Bermuda", bandera: "https://flagcdn.com/w320/bm.png", continente: "North America", capital: "Hamilton", subregion: "North America", area: 54, poblacion: 63903 },
	{id: "VEN", nombre: "Venezuela", bandera: "https://flagcdn.com/w320/ve.png", continente: "South America", capital: "Caracas", subregion: "South America", area: 916445, poblacion: 28435943 },
	{id: "SGP", nombre: "Singapore", bandera: "https://flagcdn.com/w320/sg.png", continente: "Asia", capital: "Singapore", subregion: "South-Eastern Asia", area: 710, poblacion: 5685807 },
	{id: "FSM", nombre: "Micronesia", bandera: "https://flagcdn.com/w320/fm.png", continente: "Oceania", capital: "Palikir", subregion: "Micronesia", area: 702, poblacion: 115021 },
	{id: "CUW", nombre: "Curaçao", bandera: "https://flagcdn.com/w320/cw.png", continente: "North America", capital: "Willemstad", subregion: "Caribbean", area: 444, poblacion: 155014 },
	{id: "GNQ", nombre: "Equatorial Guinea", bandera: "https://flagcdn.com/w320/gq.png", continente: "Africa", capital: "Malabo", subregion: "Middle Africa", area: 28051, poblacion: 1402985 },
	{id: "PCN", nombre: "Pitcairn Islands", bandera: "https://flagcdn.com/w320/pn.png", continente: "Oceania", capital: "Adamstown", subregion: "Polynesia", area: 47, poblacion: 56 },
	{id: "SDN", nombre: "Sudan", bandera: "https://flagcdn.com/w320/sd.png", continente: "Africa", capital: "Khartoum", subregion: "Northern Africa", area: 1886068, poblacion: 43849269 },
	{id: "BRA", nombre: "Brazil", bandera: "https://flagcdn.com/w320/br.png", continente: "South America", capital: "Brasília", subregion: "South America", area: 8515767, poblacion: 212559409 },
	{id: "ETH", nombre: "Ethiopia", bandera: "https://flagcdn.com/w320/et.png", continente: "Africa", capital: "Addis Ababa", subregion: "Eastern Africa", area: 1104300, poblacion: 114963583 },
	{id: "LUX", nombre: "Luxembourg", bandera: "https://flagcdn.com/w320/lu.png", continente: "Europe", capital: "Luxembourg", subregion: "Western Europe", area: 2586, poblacion: 632275 },
	{id: "PRT", nombre: "Portugal", bandera: "https://flagcdn.com/w320/pt.png", continente: "Europe", capital: "Lisbon", subregion: "Southern Europe", area: 92090, poblacion: 10305564 },
	{id: "DOM", nombre: "Dominican Republic", bandera: "https://flagcdn.com/w320/do.png", continente: "North America", capital: "Santo Domingo", subregion: "Caribbean", area: 48671, poblacion: 10847904 },
	{id: "BLR", nombre: "Belarus", bandera: "https://flagcdn.com/w320/by.png", continente: "Europe", capital: "Minsk", subregion: "Eastern Europe", area: 207600, poblacion: 9398861 },
	{id: "SRB", nombre: "Serbia", bandera: "https://flagcdn.com/w320/rs.png", continente: "Europe", capital: "Belgrade", subregion: "Southeast Europe", area: 88361, poblacion: 6908224 },
	{id: "GMB", nombre: "Gambia", bandera: "https://flagcdn.com/w320/gm.png", continente: "Africa", capital: "Banjul", subregion: "Western Africa", area: 10689, poblacion: 2416664 },
	{id: "NGA", nombre: "Nigeria", bandera: "https://flagcdn.com/w320/ng.png", continente: "Africa", capital: "Abuja", subregion: "Western Africa", area: 923768, poblacion: 206139587 },
	{id: "GRC", nombre: "Greece", bandera: "https://flagcdn.com/w320/gr.png", continente: "Europe", capital: "Athens", subregion: "Southern Europe", area: 131990, poblacion: 10715549 },
	{id: "REU", nombre: "Réunion", bandera: "https://flagcdn.com/w320/re.png", continente: "Africa", capital: "Saint-Denis", subregion: "Eastern Africa", area: 2511, poblacion: 840974 },
	{id: "TZA", nombre: "Tanzania", bandera: "https://flagcdn.com/w320/tz.png", continente: "Africa", capital: "Dodoma", subregion: "Eastern Africa", area: 945087, poblacion: 59734213 },
	{id: "CCK", nombre: "Cocos (Keeling) Islands", bandera: "https://flagcdn.com/w320/cc.png", continente: "Asia", capital: "West Island", subregion: "Australia and New Zealand", area: 14, poblacion: 544 },
	{id: "AGO", nombre: "Angola", bandera: "https://flagcdn.com/w320/ao.png", continente: "Africa", capital: "Luanda", subregion: "Middle Africa", area: 1246700, poblacion: 32866268 },
	{id: "BHS", nombre: "Bahamas", bandera: "https://flagcdn.com/w320/bs.png", continente: "North America", capital: "Nassau", subregion: "Caribbean", area: 13943, poblacion: 393248 },
	{id: "SHN", nombre: "Saint Helena, Ascension and Tristan da Cunha", bandera: "https://flagcdn.com/w320/sh.png", continente: "Africa", capital: "Jamestown", subregion: "Western Africa", area: 394, poblacion: 53192 },
	{id: "TUN", nombre: "Tunisia", bandera: "https://flagcdn.com/w320/tn.png", continente: "Africa", capital: "Tunis", subregion: "Northern Africa", area: 163610, poblacion: 11818618 },
	{id: "UNK", nombre: "Kosovo", bandera: "https://flagcdn.com/w320/xk.png", continente: "Europe", capital: "Pristina", subregion: "Southeast Europe", area: 10908, poblacion: 1775378 },
	{id: "TWN", nombre: "Taiwan", bandera: "https://flagcdn.com/w320/tw.png", continente: "Asia", capital: "Taipei", subregion: "Eastern Asia", area: 36193, poblacion: 23503349 },
	{id: "KIR", nombre: "Kiribati", bandera: "https://flagcdn.com/w320/ki.png", continente: "Oceania", capital: "South Tarawa", subregion: "Micronesia", area: 811, poblacion: 119446 },
	{id: "VAT", nombre: "Vatican City", bandera: "https://flagcdn.com/w320/va.png", continente: "Europe", capital: "Vatican City", subregion: "Southern Europe", area: 0, poblacion: 451 },
	{id: "BRB", nombre: "Barbados", bandera: "https://flagcdn.com/w320/bb.png", continente: "North America", capital: "Bridgetown", subregion: "Caribbean", area: 430, poblacion: 287371 },
	{id: "MLI", nombre: "Mali", bandera: "https://flagcdn.com/w320/ml.png", continente: "Africa", capital: "Bamako", subregion: "Western Africa", area: 1240192, poblacion: 20250834 },
	{id: "BTN", nombre: "Bhutan", bandera: "https://flagcdn.com/w320/bt.png", continente: "Asia", capital: "Thimphu", subregion: "Southern Asia", area: 38394, poblacion: 771612 },
	{id: "NIU", nombre: "Niue", bandera: "https://flagcdn.com/w320/nu.png", continente: "Oceania", capital: "Alofi", subregion: "Polynesia", area: 260, poblacion: 1470 },
	{id: "ARE", nombre: "United Arab Emirates", bandera: "https://flagcdn.com/w320/ae.png", continente: "Asia", capital: "Abu Dhabi", subregion: "Western Asia", area: 83600, poblacion: 9890400 },
	{id: "BEN", nombre: "Benin", bandera: "https://flagcdn.com/w320/bj.png", continente: "Africa", capital: "Porto-Novo", subregion: "Western Africa", area: 112622, poblacion: 12123198 },
	{id: "GNB", nombre: "Guinea-Bissau", bandera: "https://flagcdn.com/w320/gw.png", continente: "Africa", capital: "Bissau", subregion: "Western Africa", area: 36125, poblacion: 1967998 },
	{id: "ATF", nombre: "French Southern and Antarctic Lands", bandera: "https://flagcdn.com/w320/tf.png", continente: "Antarctica", capital: "Port-aux-Français", subregion: "Sin Subregion", area: 7747, poblacion: 400 },
	{id: "SSD", nombre: "South Sudan", bandera: "https://flagcdn.com/w320/ss.png", continente: "Africa", capital: "Juba", subregion: "Middle Africa", area: 619745, poblacion: 11193729 },
	{id: "BEL", nombre: "Belgium", bandera: "https://flagcdn.com/w320/be.png", continente: "Europe", capital: "Brussels", subregion: "Western Europe", area: 30528, poblacion: 11555997 },
	{id: "PNG", nombre: "Papua New Guinea", bandera: "https://flagcdn.com/w320/pg.png", continente: "Oceania", capital: "Port Moresby", subregion: "Melanesia", area: 462840, poblacion: 8947027 },
	{id: "ZWE", nombre: "Zimbabwe", bandera: "https://flagcdn.com/w320/zw.png", continente: "Africa", capital: "Harare", subregion: "Southern Africa", area: 390757, poblacion: 14862927 },
	{id: "HND", nombre: "Honduras", bandera: "https://flagcdn.com/w320/hn.png", continente: "North America", capital: "Tegucigalpa", subregion: "Central America", area: 112492, poblacion: 9904608 },
	{id: "LCA", nombre: "Saint Lucia", bandera: "https://flagcdn.com/w320/lc.png", continente: "North America", capital: "Castries", subregion: "Caribbean", area: 616, poblacion: 183629 },
	{id: "CAN", nombre: "Canada", bandera: "https://flagcdn.com/w320/ca.png", continente: "North America", capital: "Ottawa", subregion: "North America", area: 9984670, poblacion: 38005238 },
	{id: "JEY", nombre: "Jersey", bandera: "https://flagcdn.com/w320/je.png", continente: "Europe", capital: "Saint Helier", subregion: "Northern Europe", area: 116, poblacion: 100800 },
	{id: "SOM", nombre: "Somalia", bandera: "https://flagcdn.com/w320/so.png", continente: "Africa", capital: "Mogadishu", subregion: "Eastern Africa", area: 637657, poblacion: 15893219 },
	{id: "GUM", nombre: "Guam", bandera: "https://flagcdn.com/w320/gu.png", continente: "Oceania", capital: "Hagåtña", subregion: "Micronesia", area: 549, poblacion: 168783 },
	{id: "ISR", nombre: "Israel", bandera: "https://flagcdn.com/w320/il.png", continente: "Asia", capital: "Jerusalem", subregion: "Western Asia", area: 20770, poblacion: 9216900 },
	{id: "CYM", nombre: "Cayman Islands", bandera: "https://flagcdn.com/w320/ky.png", continente: "North America", capital: "George Town", subregion: "Caribbean", area: 264, poblacion: 65720 },
	{id: "ERI", nombre: "Eritrea", bandera: "https://flagcdn.com/w320/er.png", continente: "Africa", capital: "Asmara", subregion: "Eastern Africa", area: 117600, poblacion: 5352000 },
	{id: "IOT", nombre: "British Indian Ocean Territory", bandera: "https://flagcdn.com/w320/io.png", continente: "Asia", capital: "Diego Garcia", subregion: "Eastern Africa", area: 60, poblacion: 3000 },
	{id: "LBR", nombre: "Liberia", bandera: "https://flagcdn.com/w320/lr.png", continente: "Africa", capital: "Monrovia", subregion: "Western Africa", area: 111369, poblacion: 5057677 },
	{id: "SXM", nombre: "Sint Maarten", bandera: "https://flagcdn.com/w320/sx.png", continente: "North America", capital: "Philipsburg", subregion: "Caribbean", area: 34, poblacion: 40812 },
	{id: "BGD", nombre: "Bangladesh", bandera: "https://flagcdn.com/w320/bd.png", continente: "Asia", capital: "Dhaka", subregion: "Southern Asia", area: 147570, poblacion: 164689383 },
	{id: "ECU", nombre: "Ecuador", bandera: "https://flagcdn.com/w320/ec.png", continente: "South America", capital: "Quito", subregion: "South America", area: 276841, poblacion: 17643060 },
	{id: "LTU", nombre: "Lithuania", bandera: "https://flagcdn.com/w320/lt.png", continente: "Europe", capital: "Vilnius", subregion: "Northern Europe", area: 65300, poblacion: 2794700 },
	{id: "ITA", nombre: "Italy", bandera: "https://flagcdn.com/w320/it.png", continente: "Europe", capital: "Rome", subregion: "Southern Europe", area: 301336, poblacion: 59554023 },
	{id: "ISL", nombre: "Iceland", bandera: "https://flagcdn.com/w320/is.png", continente: "Europe", capital: "Reykjavik", subregion: "Northern Europe", area: 103000, poblacion: 366425 },
	{id: "MYS", nombre: "Malaysia", bandera: "https://flagcdn.com/w320/my.png", continente: "Asia", capital: "Kuala Lumpur", subregion: "South-Eastern Asia", area: 330803, poblacion: 32365998 },
	{id: "LIE", nombre: "Liechtenstein", bandera: "https://flagcdn.com/w320/li.png", continente: "Europe", capital: "Vaduz", subregion: "Western Europe", area: 160, poblacion: 38137 },
	{id: "IDN", nombre: "Indonesia", bandera: "https://flagcdn.com/w320/id.png", continente: "Asia", capital: "Jakarta", subregion: "South-Eastern Asia", area: 1904569, poblacion: 273523621 },
	{id: "KNA", nombre: "Saint Kitts and Nevis", bandera: "https://flagcdn.com/w320/kn.png", continente: "North America", capital: "Basseterre", subregion: "Caribbean", area: 261, poblacion: 53192 },
	{id: "ALB", nombre: "Albania", bandera: "https://flagcdn.com/w320/al.png", continente: "Europe", capital: "Tirana", subregion: "Southeast Europe", area: 28748, poblacion: 2837743 },
	{id: "RWA", nombre: "Rwanda", bandera: "https://flagcdn.com/w320/rw.png", continente: "Africa", capital: "Kigali", subregion: "Eastern Africa", area: 26338, poblacion: 12952209 },
	{id: "VNM", nombre: "Vietnam", bandera: "https://flagcdn.com/w320/vn.png", continente: "Asia", capital: "Hanoi", subregion: "South-Eastern Asia", area: 331212, poblacion: 97338583 },
	{id: "ZAF", nombre: "South Africa", bandera: "https://flagcdn.com/w320/za.png", continente: "Africa", capital: "Pretoria", subregion: "Southern Africa", area: 1221037, poblacion: 59308690 },
	{id: "CHE", nombre: "Switzerland", bandera: "https://flagcdn.com/w320/ch.png", continente: "Europe", capital: "Bern", subregion: "Western Europe", area: 41284, poblacion: 8654622 },
	{id: "THA", nombre: "Thailand", bandera: "https://flagcdn.com/w320/th.png", continente: "Asia", capital: "Bangkok", subregion: "South-Eastern Asia", area: 513120, poblacion: 69799978 },
	{id: "ARG", nombre: "Argentina", bandera: "https://flagcdn.com/w320/ar.png", continente: "South America", capital: "Buenos Aires", subregion: "South America", area: 2780400, poblacion: 45376763 },
	{id: "MDV", nombre: "Maldives", bandera: "https://flagcdn.com/w320/mv.png", continente: "Asia", capital: "Malé", subregion: "Southern Asia", area: 300, poblacion: 540542 },
	{id: "ATG", nombre: "Antigua and Barbuda", bandera: "https://flagcdn.com/w320/ag.png", continente: "North America", capital: "Saint John's", subregion: "Caribbean", area: 442, poblacion: 97928 },
	{id: "DNK", nombre: "Denmark", bandera: "https://flagcdn.com/w320/dk.png", continente: "Europe", capital: "Copenhagen", subregion: "Northern Europe", area: 43094, poblacion: 5831404 },
	{id: "SAU", nombre: "Saudi Arabia", bandera: "https://flagcdn.com/w320/sa.png", continente: "Asia", capital: "Riyadh", subregion: "Western Asia", area: 2149690, poblacion: 34813867 },
	{id: "COL", nombre: "Colombia", bandera: "https://flagcdn.com/w320/co.png", continente: "South America", capital: "Bogotá", subregion: "South America", area: 1141748, poblacion: 50882884 },
	{id: "LBY", nombre: "Libya", bandera: "https://flagcdn.com/w320/ly.png", continente: "Africa", capital: "Tripoli", subregion: "Northern Africa", area: 1759540, poblacion: 6871287 },
	{id: "MKD", nombre: "North Macedonia", bandera: "https://flagcdn.com/w320/mk.png", continente: "Europe", capital: "Skopje", subregion: "Southeast Europe", area: 25713, poblacion: 2077132 },
	{id: "ARM", nombre: "Armenia", bandera: "https://flagcdn.com/w320/am.png", continente: "Asia", capital: "Yerevan", subregion: "Western Asia", area: 29743, poblacion: 2963234 },
	{id: "TUV", nombre: "Tuvalu", bandera: "https://flagcdn.com/w320/tv.png", continente: "Oceania", capital: "Funafuti", subregion: "Polynesia", area: 26, poblacion: 11792 },
	{id: "MAC", nombre: "Macau", bandera: "https://flagcdn.com/w320/mo.png", continente: "Asia", capital: "Sin Capital", subregion: "Eastern Asia", area: 30, poblacion: 649342 },
	{id: "AZE", nombre: "Azerbaijan", bandera: "https://flagcdn.com/w320/az.png", continente: "Asia", capital: "Baku", subregion: "Western Asia", area: 86600, poblacion: 10110116 },
	{id: "TGO", nombre: "Togo", bandera: "https://flagcdn.com/w320/tg.png", continente: "Africa", capital: "Lomé", subregion: "Western Africa", area: 56785, poblacion: 8278737 },
	{id: "DEU", nombre: "Germany", bandera: "https://flagcdn.com/w320/de.png", continente: "Europe", capital: "Berlin", subregion: "Western Europe", area: 357114, poblacion: 83240525 },
	{id: "PAK", nombre: "Pakistan", bandera: "https://flagcdn.com/w320/pk.png", continente: "Asia", capital: "Islamabad", subregion: "Southern Asia", area: 881912, poblacion: 220892331 },
	{id: "QAT", nombre: "Qatar", bandera: "https://flagcdn.com/w320/qa.png", continente: "Asia", capital: "Doha", subregion: "Western Asia", area: 11586, poblacion: 2881060 },
	{id: "HTI", nombre: "Haiti", bandera: "https://flagcdn.com/w320/ht.png", continente: "North America", capital: "Port-au-Prince", subregion: "Caribbean", area: 27750, poblacion: 11402533 },
	{id: "PSE", nombre: "Palestine", bandera: "https://flagcdn.com/w320/ps.png", continente: "Asia", capital: "Ramallah", subregion: "Western Asia", area: 6220, poblacion: 4803269 },
	{id: "LSO", nombre: "Lesotho", bandera: "https://flagcdn.com/w320/ls.png", continente: "Africa", capital: "Maseru", subregion: "Southern Africa", area: 30355, poblacion: 2142252 },
	{id: "CYP", nombre: "Cyprus", bandera: "https://flagcdn.com/w320/cy.png", continente: "Europe", capital: "Nicosia", subregion: "Southern Europe", area: 9251, poblacion: 1207361 },
	{id: "NCL", nombre: "New Caledonia", bandera: "https://flagcdn.com/w320/nc.png", continente: "Oceania", capital: "Nouméa", subregion: "Melanesia", area: 18575, poblacion: 271960 },
	{id: "JOR", nombre: "Jordan", bandera: "https://flagcdn.com/w320/jo.png", continente: "Asia", capital: "Amman", subregion: "Western Asia", area: 89342, poblacion: 10203140 },
	{id: "PER", nombre: "Peru", bandera: "https://flagcdn.com/w320/pe.png", continente: "South America", capital: "Lima", subregion: "South America", area: 1285216, poblacion: 32971846 },
	{id: "TON", nombre: "Tonga", bandera: "https://flagcdn.com/w320/to.png", continente: "Oceania", capital: "Nuku'alofa", subregion: "Polynesia", area: 747, poblacion: 105697 },
	{id: "HRV", nombre: "Croatia", bandera: "https://flagcdn.com/w320/hr.png", continente: "Europe", capital: "Zagreb", subregion: "Southeast Europe", area: 56594, poblacion: 4047200 },
	{id: "MTQ", nombre: "Martinique", bandera: "https://flagcdn.com/w320/mq.png", continente: "North America", capital: "Fort-de-France", subregion: "Caribbean", area: 1128, poblacion: 378243 },
	{id: "SYC", nombre: "Seychelles", bandera: "https://flagcdn.com/w320/sc.png", continente: "Africa", capital: "Victoria", subregion: "Eastern Africa", area: 452, poblacion: 98462 },
	{id: "WLF", nombre: "Wallis and Futuna", bandera: "https://flagcdn.com/w320/wf.png", continente: "Oceania", capital: "Mata-Utu", subregion: "Polynesia", area: 142, poblacion: 11750 },
	{id: "MUS", nombre: "Mauritius", bandera: "https://flagcdn.com/w320/mu.png", continente: "Africa", capital: "Port Louis", subregion: "Eastern Africa", area: 2040, poblacion: 1265740 },
	{id: "SPM", nombre: "Saint Pierre and Miquelon", bandera: "https://flagcdn.com/w320/pm.png", continente: "North America", capital: "Saint-Pierre", subregion: "North America", area: 242, poblacion: 6069 },
	{id: "VUT", nombre: "Vanuatu", bandera: "https://flagcdn.com/w320/vu.png", continente: "Oceania", capital: "Port Vila", subregion: "Melanesia", area: 12189, poblacion: 307150 },
	{id: "SVN", nombre: "Slovenia", bandera: "https://flagcdn.com/w320/si.png", continente: "Europe", capital: "Ljubljana", subregion: "Central Europe", area: 20273, poblacion: 2100126 },
	{id: "SLE", nombre: "Sierra Leone", bandera: "https://flagcdn.com/w320/sl.png", continente: "Africa", capital: "Freetown", subregion: "Western Africa", area: 71740, poblacion: 7976985 },
	{id: "VGB", nombre: "British Virgin Islands", bandera: "https://flagcdn.com/w320/vg.png", continente: "North America", capital: "Road Town", subregion: "Caribbean", area: 151, poblacion: 30237 },
	{id: "IRQ", nombre: "Iraq", bandera: "https://flagcdn.com/w320/iq.png", continente: "Asia", capital: "Baghdad", subregion: "Western Asia", area: 438317, poblacion: 40222503 },
	{id: "SJM", nombre: "Svalbard and Jan Mayen", bandera: "https://flagcdn.com/w320/sj.png", continente: "Europe", capital: "Longyearbyen", subregion: "Northern Europe", area: -1, poblacion: 2562 },
	{id: "HUN", nombre: "Hungary", bandera: "https://flagcdn.com/w320/hu.png", continente: "Europe", capital: "Budapest", subregion: "Central Europe", area: 93028, poblacion: 9749763 },
	{id: "UMI", nombre: "United States Minor Outlying Islands", bandera: "https://flagcdn.com/w320/um.png", continente: "Oceania", capital: "Sin Capital", subregion: "North America", area: 34, poblacion: 300 },
	{id: "GAB", nombre: "Gabon", bandera: "https://flagcdn.com/w320/ga.png", continente: "Africa", capital: "Libreville", subregion: "Middle Africa", area: 267668, poblacion: 2225728 },
	{id: "GIB", nombre: "Gibraltar", bandera: "https://flagcdn.com/w320/gi.png", continente: "Europe", capital: "Gibraltar", subregion: "Southern Europe", area: 6, poblacion: 33691 },
	{id: "SMR", nombre: "San Marino", bandera: "https://flagcdn.com/w320/sm.png", continente: "Europe", capital: "City of San Marino", subregion: "Southern Europe", area: 61, poblacion: 33938 },
	{id: "MSR", nombre: "Montserrat", bandera: "https://flagcdn.com/w320/ms.png", continente: "North America", capital: "Plymouth", subregion: "Caribbean", area: 102, poblacion: 4922 },
	{id: "COK", nombre: "Cook Islands", bandera: "https://flagcdn.com/w320/ck.png", continente: "Oceania", capital: "Avarua", subregion: "Polynesia", area: 236, poblacion: 18100 },
	{id: "BIH", nombre: "Bosnia and Herzegovina", bandera: "https://flagcdn.com/w320/ba.png", continente: "Europe", capital: "Sarajevo", subregion: "Southeast Europe", area: 51209, poblacion: 3280815 },
	{id: "MNE", nombre: "Montenegro", bandera: "https://flagcdn.com/w320/me.png", continente: "Europe", capital: "Podgorica", subregion: "Southeast Europe", area: 13812, poblacion: 621718 },
	{id: "MNG", nombre: "Mongolia", bandera: "https://flagcdn.com/w320/mn.png", continente: "Asia", capital: "Ulan Bator", subregion: "Eastern Asia", area: 1564110, poblacion: 3278292 },
	{id: "PLW", nombre: "Palau", bandera: "https://flagcdn.com/w320/pw.png", continente: "Oceania", capital: "Ngerulmud", subregion: "Micronesia", area: 459, poblacion: 18092 },
	{id: "TLS", nombre: "Timor-Leste", bandera: "https://flagcdn.com/w320/tl.png", continente: "Oceania", capital: "Dili", subregion: "South-Eastern Asia", area: 14874, poblacion: 1318442 },
	{id: "PRY", nombre: "Paraguay", bandera: "https://flagcdn.com/w320/py.png", continente: "South America", capital: "Asunción", subregion: "South America", area: 406752, poblacion: 7132530 },
	{id: "HKG", nombre: "Hong Kong", bandera: "https://flagcdn.com/w320/hk.png", continente: "Asia", capital: "City of Victoria", subregion: "Eastern Asia", area: 1104, poblacion: 7500700 },
	{id: "SUR", nombre: "Suriname", bandera: "https://flagcdn.com/w320/sr.png", continente: "South America", capital: "Paramaribo", subregion: "South America", area: 163820, poblacion: 586634 },
	{id: "MEX", nombre: "Mexico", bandera: "https://flagcdn.com/w320/mx.png", continente: "North America", capital: "Mexico City", subregion: "North America", area: 1964375, poblacion: 128932753 },
	{id: "UGA", nombre: "Uganda", bandera: "https://flagcdn.com/w320/ug.png", continente: "Africa", capital: "Kampala", subregion: "Eastern Africa", area: 241550, poblacion: 45741000 },
	{id: "KHM", nombre: "Cambodia", bandera: "https://flagcdn.com/w320/kh.png", continente: "Asia", capital: "Phnom Penh", subregion: "South-Eastern Asia", area: 181035, poblacion: 16718971 },
	{id: "POL", nombre: "Poland", bandera: "https://flagcdn.com/w320/pl.png", continente: "Europe", capital: "Warsaw", subregion: "Central Europe", area: 312679, poblacion: 37950802 },
	{id: "MAF", nombre: "Saint Martin", bandera: "https://flagcdn.com/w320/mf.png", continente: "North America", capital: "Marigot", subregion: "Caribbean", area: 53, poblacion: 38659 },
	{id: "COD", nombre: "DR Congo", bandera: "https://flagcdn.com/w320/cd.png", continente: "Africa", capital: "Kinshasa", subregion: "Middle Africa", area: 2344858, poblacion: 89561404 },
	{id: "MRT", nombre: "Mauritania", bandera: "https://flagcdn.com/w320/mr.png", continente: "Africa", capital: "Nouakchott", subregion: "Western Africa", area: 1030700, poblacion: 4649660 },
	{id: "MNP", nombre: "Northern Mariana Islands", bandera: "https://flagcdn.com/w320/mp.png", continente: "Oceania", capital: "Saipan", subregion: "Micronesia", area: 464, poblacion: 57557 },
	{id: "SWE", nombre: "Sweden", bandera: "https://flagcdn.com/w320/se.png", continente: "Europe", capital: "Stockholm", subregion: "Northern Europe", area: 450295, poblacion: 10353442 },
	{id: "TCD", nombre: "Chad", bandera: "https://flagcdn.com/w320/td.png", continente: "Africa", capital: "N'Djamena", subregion: "Middle Africa", area: 1284000, poblacion: 16425859 },
	{id: "GHA", nombre: "Ghana", bandera: "https://flagcdn.com/w320/gh.png", continente: "Africa", capital: "Accra", subregion: "Western Africa", area: 238533, poblacion: 31072945 },
	{id: "PAN", nombre: "Panama", bandera: "https://flagcdn.com/w320/pa.png", continente: "North America", capital: "Panama City", subregion: "Central America", area: 75417, poblacion: 4314768 },
	{id: "LAO", nombre: "Laos", bandera: "https://flagcdn.com/w320/la.png", continente: "Asia", capital: "Vientiane", subregion: "South-Eastern Asia", area: 236800, poblacion: 7275556 },
	{id: "MDG", nombre: "Madagascar", bandera: "https://flagcdn.com/w320/mg.png", continente: "Africa", capital: "Antananarivo", subregion: "Eastern Africa", area: 587041, poblacion: 27691019 },
	{id: "NPL", nombre: "Nepal", bandera: "https://flagcdn.com/w320/np.png", continente: "Asia", capital: "Kathmandu", subregion: "Southern Asia", area: 147181, poblacion: 29136808 },
	{id: "WSM", nombre: "Samoa", bandera: "https://flagcdn.com/w320/ws.png", continente: "Oceania", capital: "Apia", subregion: "Polynesia", area: 2842, poblacion: 198410 },
	{id: "TKL", nombre: "Tokelau", bandera: "https://flagcdn.com/w320/tk.png", continente: "Oceania", capital: "Fakaofo", subregion: "Polynesia", area: 12, poblacion: 1411 },
	{id: "BWA", nombre: "Botswana", bandera: "https://flagcdn.com/w320/bw.png", continente: "Africa", capital: "Gaborone", subregion: "Southern Africa", area: 582000, poblacion: 2351625 },
	{id: "CPV", nombre: "Cape Verde", bandera: "https://flagcdn.com/w320/cv.png", continente: "Africa", capital: "Praia", subregion: "Western Africa", area: 4033, poblacion: 555988 },
	{id: "SVK", nombre: "Slovakia", bandera: "https://flagcdn.com/w320/sk.png", continente: "Europe", capital: "Bratislava", subregion: "Central Europe", area: 49037, poblacion: 5458827 },
	{id: "BRN", nombre: "Brunei", bandera: "https://flagcdn.com/w320/bn.png", continente: "Asia", capital: "Bandar Seri Begawan", subregion: "South-Eastern Asia", area: 5765, poblacion: 437483 },
	{id: "CIV", nombre: "Ivory Coast", bandera: "https://flagcdn.com/w320/ci.png", continente: "Africa", capital: "Yamoussoukro", subregion: "Western Africa", area: 322463, poblacion: 26378275 },
	{id: "ZMB", nombre: "Zambia", bandera: "https://flagcdn.com/w320/zm.png", continente: "Africa", capital: "Lusaka", subregion: "Eastern Africa", area: 752612, poblacion: 18383956 },
	{id: "EGY", nombre: "Egypt", bandera: "https://flagcdn.com/w320/eg.png", continente: "Africa", capital: "Cairo", subregion: "Northern Africa", area: 1002450, poblacion: 102334403 },
	{id: "GUF", nombre: "French Guiana", bandera: "https://flagcdn.com/w320/gf.png", continente: "South America", capital: "Cayenne", subregion: "South America", area: 83534, poblacion: 254541 },
	{id: "KAZ", nombre: "Kazakhstan", bandera: "https://flagcdn.com/w320/kz.png", continente: "Asia", capital: "Nur-Sultan", subregion: "Central Asia", area: 2724900, poblacion: 18754440 },
	{id: "BES", nombre: "Caribbean Netherlands", bandera: "https://flagcdn.com/w320/bq.png", continente: "North America", capital: "Kralendijk", subregion: "Caribbean", area: 328, poblacion: 25987 },
	{id: "CXR", nombre: "Christmas Island", bandera: "https://flagcdn.com/w320/cx.png", continente: "Asia", capital: "Flying Fish Cove", subregion: "Australia and New Zealand", area: 135, poblacion: 2072 },
	{id: "SLB", nombre: "Solomon Islands", bandera: "https://flagcdn.com/w320/sb.png", continente: "Oceania", capital: "Honiara", subregion: "Melanesia", area: 28896, poblacion: 686878 },
	{id: "BHR", nombre: "Bahrain", bandera: "https://flagcdn.com/w320/bh.png", continente: "Asia", capital: "Manama", subregion: "Western Asia", area: 765, poblacion: 1701583 },
	{id: "GEO", nombre: "Georgia", bandera: "https://flagcdn.com/w320/ge.png", continente: "Asia", capital: "Tbilisi", subregion: "Western Asia", area: 69700, poblacion: 3714000 },
	{id: "NOR", nombre: "Norway", bandera: "https://flagcdn.com/w320/no.png", continente: "Europe", capital: "Oslo", subregion: "Northern Europe", area: 323802, poblacion: 5379475 },
	{id: "IND", nombre: "India", bandera: "https://flagcdn.com/w320/in.png", continente: "Asia", capital: "New Delhi", subregion: "Southern Asia", area: 3287590, poblacion: 1380004385 },
	{id: "MCO", nombre: "Monaco", bandera: "https://flagcdn.com/w320/mc.png", continente: "Europe", capital: "Monaco", subregion: "Western Europe", area: 2, poblacion: 39244 },
	{id: "DMA", nombre: "Dominica", bandera: "https://flagcdn.com/w320/dm.png", continente: "North America", capital: "Roseau", subregion: "Caribbean", area: 751, poblacion: 71991 },
	{id: "SWZ", nombre: "Eswatini", bandera: "https://flagcdn.com/w320/sz.png", continente: "Africa", capital: "Mbabane", subregion: "Southern Africa", area: 17364, poblacion: 1160164 },
	{id: "CRI", nombre: "Costa Rica", bandera: "https://flagcdn.com/w320/cr.png", continente: "North America", capital: "San José", subregion: "Central America", area: 51100, poblacion: 5094114 },
	{id: "PRK", nombre: "North Korea", bandera: "https://flagcdn.com/w320/kp.png", continente: "Asia", capital: "Pyongyang", subregion: "Eastern Asia", area: 120538, poblacion: 25778815 },
	{id: "GIN", nombre: "Guinea", bandera: "https://flagcdn.com/w320/gn.png", continente: "Africa", capital: "Conakry", subregion: "Western Africa", area: 245857, poblacion: 13132792 },
	{id: "LVA", nombre: "Latvia", bandera: "https://flagcdn.com/w320/lv.png", continente: "Europe", capital: "Riga", subregion: "Northern Europe", area: 64559, poblacion: 1901548 },
	{id: "NFK", nombre: "Norfolk Island", bandera: "https://flagcdn.com/w320/nf.png", continente: "Oceania", capital: "Kingston", subregion: "Australia and New Zealand", area: 36, poblacion: 2302 },
	{id: "ATA", nombre: "Antarctica", bandera: "https://flagcdn.com/w320/aq.png", continente: "Antarctica", capital: "Sin Capital", subregion: "Sin Subregion", area: 14000000, poblacion: 1000 },
	{id: "KGZ", nombre: "Kyrgyzstan", bandera: "https://flagcdn.com/w320/kg.png", continente: "Asia", capital: "Bishkek", subregion: "Central Asia", area: 199951, poblacion: 6591600 },
	{id: "GGY", nombre: "Guernsey", bandera: "https://flagcdn.com/w320/gg.png", continente: "Europe", capital: "St. Peter Port", subregion: "Northern Europe", area: 78, poblacion: 62999 },
	{id: "SEN", nombre: "Senegal", bandera: "https://flagcdn.com/w320/sn.png", continente: "Africa", capital: "Dakar", subregion: "Western Africa", area: 196722, poblacion: 16743930 },
	{id: "TUR", nombre: "Turkey", bandera: "https://flagcdn.com/w320/tr.png", continente: "Asia", capital: "Ankara", subregion: "Western Asia", area: 783562, poblacion: 84339067 },
	{id: "ALA", nombre: "Aland Islands", bandera: "https://flagcdn.com/w320/ax.png", continente: "Europe", capital: "Mariehamn", subregion: "Northern Europe", area: 1580, poblacion: 29458 },
	{id: "GRD", nombre: "Grenada", bandera: "https://flagcdn.com/w320/gd.png", continente: "North America", capital: "St. George's", subregion: "Caribbean", area: 344, poblacion: 112519 },
	{id: "JPN", nombre: "Japan", bandera: "https://flagcdn.com/w320/jp.png", continente: "Asia", capital: "Tokyo", subregion: "Eastern Asia", area: 377930, poblacion: 125836021 },
	{id: "PYF", nombre: "French Polynesia", bandera: "https://flagcdn.com/w320/pf.png", continente: "Oceania", capital: "Papeetē", subregion: "Polynesia", area: 4167, poblacion: 280904 },
	{id: "COG", nombre: "Republic of the Congo", bandera: "https://flagcdn.com/w320/cg.png", continente: "Africa", capital: "Brazzaville", subregion: "Middle Africa", area: 342000, poblacion: 89561404 },
	{id: "URY", nombre: "Uruguay", bandera: "https://flagcdn.com/w320/uy.png", continente: "South America", capital: "Montevideo", subregion: "South America", area: 181034, poblacion: 3473727 },
	{id: "NER", nombre: "Niger", bandera: "https://flagcdn.com/w320/ne.png", continente: "Africa", capital: "Niamey", subregion: "Western Africa", area: 1267000, poblacion: 24206636 },
	{id: "SLV", nombre: "El Salvador", bandera: "https://flagcdn.com/w320/sv.png", continente: "North America", capital: "San Salvador", subregion: "Central America", area: 21041, poblacion: 6486201 },
	{id: "AUS", nombre: "Australia", bandera: "https://flagcdn.com/w320/au.png", continente: "Oceania", capital: "Canberra", subregion: "Australia and New Zealand", area: 7692024, poblacion: 25687041 },
	{id: "LBN", nombre: "Lebanon", bandera: "https://flagcdn.com/w320/lb.png", continente: "Asia", capital: "Beirut", subregion: "Western Asia", area: 10452, poblacion: 6825442 },
	{id: "CMR", nombre: "Cameroon", bandera: "https://flagcdn.com/w320/cm.png", continente: "Africa", capital: "Yaoundé", subregion: "Middle Africa", area: 475442, poblacion: 26545864 },
	{id: "KEN", nombre: "Kenya", bandera: "https://flagcdn.com/w320/ke.png", continente: "Africa", capital: "Nairobi", subregion: "Eastern Africa", area: 580367, poblacion: 53771300 },
	{id: "BDI", nombre: "Burundi", bandera: "https://flagcdn.com/w320/bi.png", continente: "Africa", capital: "Gitega", subregion: "Eastern Africa", area: 27834, poblacion: 11890781 },
	{id: "GTM", nombre: "Guatemala", bandera: "https://flagcdn.com/w320/gt.png", continente: "North America", capital: "Guatemala City", subregion: "Central America", area: 108889, poblacion: 16858333 },
	{id: "OMN", nombre: "Oman", bandera: "https://flagcdn.com/w320/om.png", continente: "Asia", capital: "Muscat", subregion: "Western Asia", area: 309500, poblacion: 5106622 },
	{id: "UZB", nombre: "Uzbekistan", bandera: "https://flagcdn.com/w320/uz.png", continente: "Asia", capital: "Tashkent", subregion: "Central Asia", area: 447400, poblacion: 34232050 },
	{id: "MHL", nombre: "Marshall Islands", bandera: "https://flagcdn.com/w320/mh.png", continente: "Oceania", capital: "Majuro", subregion: "Micronesia", area: 181, poblacion: 59194 },
];

const initialState = { detail: [], listaActividades: [], getByName: [],
	backupPaises: arrayPaises,
	paises: arrayPaises,
};

const rootReducer = (state = initialState, action) => {
  switch (action.type) {
    case GET_PAISES:
      return { ...state, paises: action.payload, backupPaises: action.payload };

    case GET_BY_NAME:
      return { ...state, getByName: action.payload };

    case FILTER_BY_CONTINENT:
      return { ...state, paises: action.payload, };

    case ORDER_BY_NAME:
      return { ...state, paises: action.payload, };

    case ORDER_BY_POPULATION:
      return { ...state, paises: action.payload, };

    case GET_DETAILS:
      return { ...state, detail: action.payload };

    case GET_LIST_ATIVITIES:
      return { ...state, listaActividades: action.payload }

    case FILTER_BY_ACTIVITIES:
      return { ...state, paises: action.payload };

    default:
      return { ...state };
  }
};

export default rootReducer;
